export const USER_UPDATE_PROFILE='USER_UPDATE_PROFILE'

export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR='USER_LOGIN_ERROR'

export const USER_LOGOUT='USER_LOGOUT'

export const MARK_ATTENDANCE= 'MARK_ATTENDANCE'
export const SEE_ATTENDANCE='SEE_ATTENDANCE'
export const SEE_ATTENDANCE_ERROR='SEE_ATTENDANCE_ERROR'
export const SEE_ATTENDANCE_LOADING='SEE_ATTENDANCE_LOADING'

export const ADD_CLASS_SUCCESS='ADD_CLASS_SUCCESS'
export const ADD_CLASS_ERROR='ADD_CLASS_ERROR'

export const PARTICULAR_CLASS_SUCCESS='PARTICULAR_CLASS_SUCCESS'
export const PARTICULAR_CLASS_ERROR='PARTICULAR_CLASS_ERROR'

export const ADD_SUBJECT='ADD_SUBJECT'
export const EDIT_SUBJECT='EDIT_SUBJECT'
export const DELETE_SUBJECT='DELETE_SUBJECT'
export const ERROR_SUBJECT='ERROR_SUBJECT'
export const GET_SUBJECT='GET_SUBJECT'